name: Deno Lint (Edge Functions)

on:
  push:
    branches: [main]
    paths:
      - 'server/supabase/functions/**'
  pull_request:
    branches: [main]
    paths:
      - 'server/supabase/functions/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v1.x

      - name: Deno Version
        run: deno --version

      - name: Format Check
        run: deno fmt --check server/supabase/functions

      - name: Lint
        run: deno lint server/supabase/functions
